# Generated by Django 4.1.7 on 2023-04-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('stid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('s1_t', models.CharField(max_length=100)),
                ('s1_e', models.CharField(max_length=100)),
                ('s1_h', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1_tmarks', models.IntegerField()),
                ('s1_emarks', models.IntegerField()),
                ('s1_hmarks', models.IntegerField()),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjects')),
            ],
        ),
    ]
